name: build_nds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: rom
          path: "*.nds"
          if-no-files-found: error
